### ISSUE TITLE
Mod-Manager: Ability to pull mods.json from github.

### ISSUE THREAD

**Issue by Modulator-Mocker-Ellipse8** [josh-abram/arma-automation#12]
Ability to pull mods.json from github. Bake into the ansible perhaps?

**Comment by josh-abram** [comment]
Would be nice for more advanced users but honestly most people won't be familiar with GIT. Lets leave on the project board but low priority.

**Comment by Modulator-Mocker-Ellipse8** [comment]
Able to pull from any URL now, provided it is valid JSON.
