### ISSUE TITLE
Ansible: Stop running as root, make any sudoer supported.

### ISSUE THREAD

**Issue by Modulator-Mocker-Ellipse8** [josh-abram/arma-automation#6]
Stop running as root, make any sudoer supported.

**Comment by Modulator-Mocker-Ellipse8** [comment]
Any sudoer seems to be supported at the moment anyway, so I think this can just be resolved?

**Comment by josh-abram** [comment]
Upon further testing, any sudoer actually works. It's up to the user to supply the username of the account to run under. Probably just need to make this clear in the readme.
